import { useMemo, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'
import * as THREE from 'three'
import { origin, regions } from '../../data/topology'
import borders from '../../data/borders.json'

const R = 1.6
const BLUE = '#3161e4'
const PURPLE = '#ad07ef'

/** Lat/lon (degrees) -> point on a sphere of radius `r`. */
function toVec3(lat, lon, r = R) {
  const phi = (90 - lat) * (Math.PI / 180)
  const theta = (lon + 180) * (Math.PI / 180)
  return new THREE.Vector3(
    -r * Math.sin(phi) * Math.cos(theta),
    r * Math.cos(phi),
    r * Math.sin(phi) * Math.sin(theta),
  )
}

/**
 * Country borders and coastlines, projected onto the sphere as line segments.
 * Source data is generated by scripts/generate-borders.mjs.
 */
function Borders() {
  const geometry = useMemo(() => {
    const positions = []
    // Lift very slightly off the surface so lines don't z-fight the sphere.
    const r = R * 1.002

    for (const flat of borders) {
      for (let i = 0; i + 3 < flat.length; i += 2) {
        const a = toVec3(flat[i + 1], flat[i], r)
        const b = toVec3(flat[i + 3], flat[i + 2], r)
        // Skip the seam artefact where a polyline wraps the antimeridian.
        if (a.distanceTo(b) > R * 0.6) continue
        positions.push(a.x, a.y, a.z, b.x, b.y, b.z)
      }
    }

    const geo = new THREE.BufferGeometry()
    geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
    return geo
  }, [])

  return (
    <lineSegments geometry={geometry}>
      <lineBasicMaterial color="#8aa2d8" transparent opacity={0.55} />
    </lineSegments>
  )
}

/**
 * Arc from the origin to a destination region, lifted off the surface. A
 * travelling dot runs along it to read as live traffic.
 */
function Arc({ to, delay = 0 }) {
  const dot = useRef(null)
  const line = useRef(null)

  const curve = useMemo(() => {
    const a = toVec3(origin.lat, origin.lon)
    const b = toVec3(to.lat, to.lon)
    const mid = a.clone().add(b).multiplyScalar(0.5)
    // Longer hops arc higher so they stay clear of the surface.
    const lift = 1 + 0.55 * (a.distanceTo(b) / (2 * R))
    mid.normalize().multiplyScalar(R * (1 + 0.3 * lift))
    return new THREE.QuadraticBezierCurve3(a, mid, b)
  }, [to])

  const geometry = useMemo(() => new THREE.TubeGeometry(curve, 64, 0.011, 8, false), [curve])

  useFrame((state) => {
    const t = (state.clock.elapsedTime * 0.28 + delay) % 1
    if (dot.current) dot.current.position.copy(curve.getPointAt(t))
    if (line.current) line.current.opacity = 0.42 + Math.sin(state.clock.elapsedTime * 1.4 + delay * 6) * 0.16
  })

  return (
    <group>
      <mesh geometry={geometry}>
        <meshBasicMaterial ref={line} color={PURPLE} transparent opacity={0.5} />
      </mesh>
      <mesh ref={dot}>
        <sphereGeometry args={[0.035, 12, 12]} />
        <meshBasicMaterial color="#ffffff" />
      </mesh>
    </group>
  )
}

function Marker({ point, origin: isOrigin = false }) {
  const pos = useMemo(() => toVec3(point.lat, point.lon), [point])
  const halo = useRef(null)

  useFrame((state) => {
    if (!halo.current) return
    const pulse = 1 + Math.sin(state.clock.elapsedTime * 2 + point.lat) * 0.28
    halo.current.scale.setScalar(pulse)
  })

  return (
    <group position={pos}>
      <mesh>
        <sphereGeometry args={[isOrigin ? 0.062 : 0.048, 16, 16]} />
        <meshBasicMaterial color="#ffffff" />
      </mesh>
      <mesh ref={halo}>
        <sphereGeometry args={[isOrigin ? 0.12 : 0.09, 16, 16]} />
        <meshBasicMaterial color={isOrigin ? PURPLE : BLUE} transparent opacity={0.4} />
      </mesh>
    </group>
  )
}

export default function GlobeScene() {
  const group = useRef(null)

  useFrame((_, delta) => {
    if (group.current) group.current.rotation.y += delta * 0.07
  })

  return (
    <>
      <ambientLight intensity={0.7} />
      <pointLight position={[4, 3, 4]} intensity={26} color={BLUE} distance={18} />
      <pointLight position={[-4, -2, -3]} intensity={20} color={PURPLE} distance={18} />

      <group ref={group} rotation={[0, -Math.PI / 2, 0]}>
        {/* Opaque core so borders on the far side stay hidden. */}
        <mesh>
          <sphereGeometry args={[R * 0.99, 48, 48]} />
          <meshBasicMaterial color="#0e1018" />
        </mesh>

        <mesh>
          <sphereGeometry args={[R, 24, 18]} />
          <meshBasicMaterial color={BLUE} wireframe transparent opacity={0.07} />
        </mesh>

        <Borders />

        <Marker point={origin} origin />
        {regions.map((r) => (
          <Marker key={r.id} point={r} />
        ))}

        {regions.map((r, i) => (
          <Arc key={r.id} to={r} delay={i * 0.33} />
        ))}
      </group>

      <OrbitControls
        enablePan={false}
        enableZoom={false}
        rotateSpeed={0.45}
        minPolarAngle={Math.PI / 5}
        maxPolarAngle={(4 * Math.PI) / 5}
      />
    </>
  )
}
