import { useMemo, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'
import * as THREE from 'three'
import { origin, regions } from '../../data/topology'
import borders from '../../data/borders.json'
import { GLOBE_PALETTES } from './globePalettes'

const R = 1.6

/** Lat/lon (degrees) -> point on a sphere of radius `r`. */
function toVec3(lat, lon, r = R) {
  const phi = (90 - lat) * (Math.PI / 180)
  const theta = (lon + 180) * (Math.PI / 180)
  return new THREE.Vector3(
    -r * Math.sin(phi) * Math.cos(theta),
    r * Math.cos(phi),
    r * Math.sin(phi) * Math.sin(theta),
  )
}

/**
 * Country borders and coastlines, projected onto the sphere as line segments.
 * Source data is generated by scripts/generate-borders.mjs.
 */
function Borders({ palette }) {
  const geometry = useMemo(() => {
    const positions = []
    // Lift very slightly off the surface so lines don't z-fight the sphere.
    const r = R * 1.002

    for (const flat of borders) {
      for (let i = 0; i + 3 < flat.length; i += 2) {
        const a = toVec3(flat[i + 1], flat[i], r)
        const b = toVec3(flat[i + 3], flat[i + 2], r)
        // Skip the seam artefact where a polyline wraps the antimeridian.
        if (a.distanceTo(b) > R * 0.6) continue
        positions.push(a.x, a.y, a.z, b.x, b.y, b.z)
      }
    }

    const geo = new THREE.BufferGeometry()
    geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
    return geo
  }, [])

  return (
    <lineSegments geometry={geometry}>
      <lineBasicMaterial color={palette.land} transparent opacity={0.85} />
    </lineSegments>
  )
}

/**
 * Great-circle arc from the origin to a destination, lifted by a sine profile.
 *
 * Deliberately NOT a quadratic Bezier: for separations beyond ~110 degrees a
 * Bezier's apex falls *inside* the sphere and the arc disappears behind the
 * globe (this is what hid the India -> NA link). Slerping the direction and
 * scaling the radius keeps every point above the surface at any separation.
 */
function Arc({ to, delay = 0, palette }) {
  const dot = useRef(null)
  const line = useRef(null)

  const curve = useMemo(() => {
    const a = toVec3(origin.lat, origin.lon)
    const b = toVec3(to.lat, to.lon)

    const na = a.clone().normalize()
    const nb = b.clone().normalize()
    const omega = Math.acos(THREE.MathUtils.clamp(na.dot(nb), -1, 1))
    const sinOmega = Math.sin(omega)

    // Longer hops arc higher, so they read clearly against the globe.
    const height = 0.14 + 0.42 * (omega / Math.PI)

    const steps = 96
    const points = []
    for (let i = 0; i <= steps; i++) {
      const t = i / steps

      // Spherical interpolation; falls back to lerp when the points coincide.
      let dir
      if (sinOmega < 1e-6) {
        dir = na.clone().lerp(nb, t).normalize()
      } else {
        const s1 = Math.sin((1 - t) * omega) / sinOmega
        const s2 = Math.sin(t * omega) / sinOmega
        dir = na.clone().multiplyScalar(s1).add(nb.clone().multiplyScalar(s2)).normalize()
      }

      const altitude = R * (1 + height * Math.sin(Math.PI * t))
      points.push(dir.multiplyScalar(altitude))
    }

    return new THREE.CatmullRomCurve3(points)
  }, [to])

  const geometry = useMemo(() => new THREE.TubeGeometry(curve, 96, 0.011, 8, false), [curve])

  useFrame((state) => {
    const t = (state.clock.elapsedTime * 0.28 + delay) % 1
    if (dot.current) dot.current.position.copy(curve.getPointAt(t))
    if (line.current) line.current.opacity = 0.45 + Math.sin(state.clock.elapsedTime * 1.4 + delay * 6) * 0.15
  })

  return (
    <group>
      <mesh geometry={geometry}>
        <meshBasicMaterial ref={line} color={palette.accent} transparent opacity={0.55} />
      </mesh>
      <mesh ref={dot}>
        <sphereGeometry args={[0.035, 12, 12]} />
        <meshBasicMaterial color={palette.dot} />
      </mesh>
    </group>
  )
}

function Marker({ point, origin: isOrigin = false, palette }) {
  const pos = useMemo(() => toVec3(point.lat, point.lon), [point])
  const halo = useRef(null)

  useFrame((state) => {
    if (!halo.current) return
    const pulse = 1 + Math.sin(state.clock.elapsedTime * 2 + point.lat) * 0.28
    halo.current.scale.setScalar(pulse)
  })

  return (
    <group position={pos}>
      <mesh>
        <sphereGeometry args={[isOrigin ? 0.062 : 0.048, 16, 16]} />
        <meshBasicMaterial color={palette.dot} />
      </mesh>
      <mesh ref={halo}>
        <sphereGeometry args={[isOrigin ? 0.12 : 0.09, 16, 16]} />
        <meshBasicMaterial color={isOrigin ? palette.accent : palette.marker} transparent opacity={0.4} />
      </mesh>
    </group>
  )
}

export default function GlobeScene({ palette = GLOBE_PALETTES.grey }) {
  const group = useRef(null)

  useFrame((_, delta) => {
    if (group.current) group.current.rotation.y += delta * 0.07
  })

  return (
    <>
      <group ref={group} rotation={[0, -Math.PI / 2, 0]}>
        {/* Opaque core so borders on the far side stay hidden. */}
        <mesh>
          <sphereGeometry args={[R * 0.99, 48, 48]} />
          <meshBasicMaterial color={palette.core} />
        </mesh>

        <mesh>
          <sphereGeometry args={[R, 24, 18]} />
          <meshBasicMaterial color={palette.land} wireframe transparent opacity={0.07} />
        </mesh>

        <Borders palette={palette} />

        <Marker point={origin} origin palette={palette} />
        {regions.map((r) => (
          <Marker key={r.id} point={r} palette={palette} />
        ))}

        {regions.map((r, i) => (
          <Arc key={r.id} to={r} delay={i * 0.33} palette={palette} />
        ))}
      </group>

      <OrbitControls
        enablePan={false}
        enableZoom={false}
        rotateSpeed={0.45}
        minPolarAngle={Math.PI / 5}
        maxPolarAngle={(4 * Math.PI) / 5}
      />
    </>
  )
}
