import { useLayoutEffect, useMemo, useRef } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'
import * as THREE from 'three'
import { endpoints, origin } from '../../data/topology'
import borders from '../../data/borders.json'
import { GLOBE_PALETTES } from './globePalettes'

const R = 1.6
const DOT = 0.028 // travelling dot radius
const FILL = 0.94 // share of the canvas half-width the outermost arc may reach
const SPIN = 0.07 // auto-rotation, radians per second
const RESUME_AFTER = 2 // seconds of idle after a drag before auto-rotation resumes

/** Lat/lon (degrees) -> point on a sphere of radius `r`. */
function toVec3(lat, lon, r = R) {
  const phi = (90 - lat) * (Math.PI / 180)
  const theta = (lon + 180) * (Math.PI / 180)
  return new THREE.Vector3(
    -r * Math.sin(phi) * Math.cos(theta),
    r * Math.cos(phi),
    r * Math.sin(phi) * Math.sin(theta),
  )
}

/** Angle between two lat/lon points, in radians. */
function separation(a, b) {
  const dot = toVec3(a.lat, a.lon, 1).dot(toVec3(b.lat, b.lon, 1))
  return Math.acos(THREE.MathUtils.clamp(dot, -1, 1))
}

/**
 * How high an arc rises at its midpoint, as a fraction of R. Proportional to
 * distance so a short hop reads as short, but capped well below the old
 * 0.14-0.56 range: those lifts carried every arc past the edge of the canvas
 * once the globe turned it side-on.
 */
const liftFor = (omega) => 0.05 + 0.2 * (omega / Math.PI)

/** Radius of a sphere that contains every arc and travelling dot. */
const ENVELOPE = R * (1 + Math.max(...endpoints.map((e) => liftFor(separation(origin, e))))) + DOT

/**
 * Pulls the camera back until the envelope fits the canvas with a margin.
 *
 * A sphere projects to the same circle from every direction, so fitting the
 * envelope (not the arcs as they currently sit) holds through auto-rotation and
 * any drag, and the globe never has to change size while it spins.
 */
function FrameEnvelope() {
  const { camera, size } = useThree()

  useLayoutEffect(() => {
    const halfV = THREE.MathUtils.degToRad(camera.fov / 2)
    const halfH = Math.atan(Math.tan(halfV) * (size.width / Math.max(size.height, 1)))
    // Angular radius the envelope may cover so its outline lands at FILL.
    const reach = Math.atan(FILL * Math.tan(Math.min(halfV, halfH)))
    camera.position.setLength(ENVELOPE / Math.sin(reach))
  }, [camera, size])

  return null
}

/**
 * Starting spin that puts the origin just right of centre. Every arc starts
 * there, so the first frame shows the hub and the fan of connections to Europe,
 * and auto-rotation then carries the view west towards the Americas.
 */
const INITIAL_SPIN = (() => {
  const o = toVec3(origin.lat, origin.lon)
  return 0.3 - Math.atan2(o.x, o.z)
})()

/**
 * Country borders and coastlines, projected onto the sphere as line segments.
 * Source data is generated by scripts/generate-borders.mjs.
 */
function Borders({ palette }) {
  const geometry = useMemo(() => {
    const positions = []
    // Lift very slightly off the surface so lines don't z-fight the sphere.
    const r = R * 1.002

    for (const flat of borders) {
      for (let i = 0; i + 3 < flat.length; i += 2) {
        const a = toVec3(flat[i + 1], flat[i], r)
        const b = toVec3(flat[i + 3], flat[i + 2], r)
        // Skip the seam artefact where a polyline wraps the antimeridian.
        if (a.distanceTo(b) > R * 0.6) continue
        positions.push(a.x, a.y, a.z, b.x, b.y, b.z)
      }
    }

    const geo = new THREE.BufferGeometry()
    geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
    return geo
  }, [])

  return (
    <lineSegments geometry={geometry}>
      <lineBasicMaterial color={palette.land} transparent opacity={0.85} />
    </lineSegments>
  )
}

/**
 * Great-circle arc from the origin to a destination, lifted by a sine profile.
 *
 * Deliberately NOT a quadratic Bezier: for separations beyond ~110 degrees a
 * Bezier's apex falls *inside* the sphere and the arc disappears behind the
 * globe (this is what hid the India -> NA link). Slerping the direction and
 * scaling the radius keeps every point above the surface at any separation.
 */
function Arc({ to, delay = 0, palette }) {
  const dot = useRef(null)
  const line = useRef(null)

  const curve = useMemo(() => {
    const na = toVec3(origin.lat, origin.lon, 1)
    const nb = toVec3(to.lat, to.lon, 1)
    const omega = separation(origin, to)
    const sinOmega = Math.sin(omega)
    const height = liftFor(omega)

    const steps = 96
    const points = []
    for (let i = 0; i <= steps; i++) {
      const t = i / steps

      // Spherical interpolation; falls back to lerp when the points coincide.
      let dir
      if (sinOmega < 1e-6) {
        dir = na.clone().lerp(nb, t).normalize()
      } else {
        const s1 = Math.sin((1 - t) * omega) / sinOmega
        const s2 = Math.sin(t * omega) / sinOmega
        dir = na.clone().multiplyScalar(s1).add(nb.clone().multiplyScalar(s2)).normalize()
      }

      const altitude = R * (1 + height * Math.sin(Math.PI * t))
      points.push(dir.multiplyScalar(altitude))
    }

    return new THREE.CatmullRomCurve3(points)
  }, [to])

  const geometry = useMemo(() => new THREE.TubeGeometry(curve, 96, 0.009, 8, false), [curve])

  useFrame((state) => {
    const t = (state.clock.elapsedTime * 0.28 + delay) % 1
    if (dot.current) dot.current.position.copy(curve.getPointAt(t))
    if (line.current) line.current.opacity = 0.45 + Math.sin(state.clock.elapsedTime * 1.4 + delay * 6) * 0.15
  })

  return (
    <group>
      <mesh geometry={geometry}>
        <meshBasicMaterial ref={line} color={palette.accent} transparent opacity={0.55} />
      </mesh>
      <mesh ref={dot}>
        <sphereGeometry args={[DOT, 12, 12]} />
        <meshBasicMaterial color={palette.dot} />
      </mesh>
    </group>
  )
}

function Marker({ point, origin: isOrigin = false, palette }) {
  const pos = useMemo(() => toVec3(point.lat, point.lon), [point])
  const halo = useRef(null)

  useFrame((state) => {
    if (!halo.current) return
    const pulse = 1 + Math.sin(state.clock.elapsedTime * 2 + point.lat) * 0.28
    halo.current.scale.setScalar(pulse)
  })

  return (
    <group position={pos}>
      <mesh>
        <sphereGeometry args={[isOrigin ? 0.058 : 0.042, 16, 16]} />
        <meshBasicMaterial color={palette.dot} />
      </mesh>
      <mesh ref={halo}>
        <sphereGeometry args={[isOrigin ? 0.1 : 0.072, 16, 16]} />
        <meshBasicMaterial color={isOrigin ? palette.accent : palette.marker} transparent opacity={0.4} />
      </mesh>
    </group>
  )
}

export default function GlobeScene({ palette = GLOBE_PALETTES.grey, interactive = true }) {
  const group = useRef(null)
  const clock = useThree((state) => state.clock)
  const dragging = useRef(false)
  const resumeAt = useRef(0)

  // Hold still while the visitor is dragging, and for a moment after, so the
  // globe doesn't slide away from whatever they turned it to look at.
  useFrame((state, delta) => {
    if (!group.current || dragging.current || state.clock.elapsedTime < resumeAt.current) return
    group.current.rotation.y += delta * SPIN
  })

  return (
    <>
      <FrameEnvelope />

      <group ref={group} rotation={[0, INITIAL_SPIN, 0]}>
        {/* Opaque core so borders on the far side stay hidden. */}
        <mesh>
          <sphereGeometry args={[R * 0.99, 48, 48]} />
          <meshBasicMaterial color={palette.core} />
        </mesh>

        <mesh>
          <sphereGeometry args={[R, 24, 18]} />
          <meshBasicMaterial color={palette.land} wireframe transparent opacity={0.07} />
        </mesh>

        <Borders palette={palette} />

        <Marker point={origin} origin palette={palette} />
        {endpoints.map((e) => (
          <Marker key={e.id} point={e} palette={palette} />
        ))}

        {endpoints.map((e, i) => (
          // Stagger the travelling dots so they don't move in lockstep.
          <Arc key={e.id} to={e} delay={i / endpoints.length} palette={palette} />
        ))}
      </group>

      {interactive && (
        <OrbitControls
          enablePan={false}
          enableZoom={false}
          rotateSpeed={0.45}
          onStart={() => {
            dragging.current = true
          }}
          onEnd={() => {
            dragging.current = false
            resumeAt.current = clock.elapsedTime + RESUME_AFTER
          }}
          minPolarAngle={Math.PI / 5}
          maxPolarAngle={(4 * Math.PI) / 5}
        />
      )}
    </>
  )
}
